package com.healthcare.backend.service;

import com.healthcare.backend.dto.AiTriageRequest;
import com.healthcare.backend.dto.AiTriageResponse;
import com.healthcare.backend.dto.TriageClassificationRequest;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestClient;

import java.util.List;

@Service
public class AiTriageService {

    private static final String DISCLAIMER =
            "This result is generated by an educational "
            + "triage-support prototype. It is not a diagnosis.";

    private final RestClient restClient;
    private final String classifyPath;

    public AiTriageService(
            RestClient aiTriageRestClient,
            @Value("${ai.triage.classify-path}")
            String classifyPath
    ) {
        this.restClient = aiTriageRestClient;
        this.classifyPath = classifyPath;
    }

    public AiTriageResponse classify(
            TriageClassificationRequest request
    ) {
        AiTriageRequest aiRequest = new AiTriageRequest(
                request.symptomText(),
                request.severity(),
                request.duration(),
                request.age(),
                request.followUpAnswers() == null
                        ? List.of()
                        : request.followUpAnswers()
        );

        try {
            AiTriageResponse response = restClient
                    .post()
                    .uri(classifyPath)
                    .body(aiRequest)
                    .retrieve()
                    .body(AiTriageResponse.class);

            if (response == null) {
                return createFallbackResponse();
            }

            return response;

        } catch (RestClientException exception) {
            System.err.println(
                    "AI service unavailable: "
                    + exception.getMessage()
            );

            return createFallbackResponse();
        }
    }

    private AiTriageResponse createFallbackResponse() {
        return new AiTriageResponse(
                "NEEDS_REVIEW",
                "The automatic classifier is temporarily unavailable. "
                        + "The case has been marked for staff review.",
                "Spring Boot could not obtain a response "
                        + "from the AI service.",
                "Automatic summary is unavailable.",
                false,
                List.of(),
                List.of(),
                0.0,
                "SPRING_BOOT_FALLBACK",
                true,
                DISCLAIMER
        );
    }
}