import re
from dataclasses import dataclass

from app.models import TriageRequest, TriageResponse, UrgencyLevel
from app.rules import (
    EMERGENCY_PHRASES,
    FAMILY_DOCTOR_PHRASES,
    KNOWN_SYMPTOMS,
    SELF_CARE_PHRASES,
    URGENT_PHRASES,
    WALK_IN_PHRASES,
)


DISCLAIMER = (
    "This result is generated by an educational triage-support prototype. "
    "It is not a diagnosis, treatment plan, prescription, or replacement "
    "for assessment by a licensed healthcare professional."
)


@dataclass
class MatchResult:
    phrases: list[str]
    explanations: list[str]


def normalize_text(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s'-]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text


def find_emergency_matches(text: str) -> MatchResult:
    phrases = []
    explanations = []

    for phrase, explanation in EMERGENCY_PHRASES.items():
        if phrase in text:
            phrases.append(phrase)
            explanations.append(explanation)

    return MatchResult(phrases=phrases, explanations=explanations)


def find_phrase_matches(text: str, phrases: set[str]) -> list[str]:
    return sorted([phrase for phrase in phrases if phrase in text])


def extract_symptoms(text: str) -> list[str]:
    return sorted([symptom for symptom in KNOWN_SYMPTOMS if symptom in text])


def has_positive_answer(request: TriageRequest, keywords: set[str]) -> bool:
    for item in request.follow_up_answers:
        combined = f"{item.question} {item.answer}".lower()

        if any(keyword in combined for keyword in keywords):
            if item.answer.strip().lower() in {
                "yes",
                "true",
                "severe",
                "very severe",
            }:
                return True

    return False


def create_summary(
    request: TriageRequest,
    symptoms: list[str],
    urgency: UrgencyLevel,
) -> str:
    symptom_part = (
        ", ".join(symptoms)
        if symptoms
        else "No standard symptom keywords were extracted"
    )

    duration_part = request.duration or "not provided"

    return (
        f"Reported text: {request.symptom_text}. "
        f"Extracted symptoms: {symptom_part}. "
        f"Reported severity: {request.severity}/5. "
        f"Duration: {duration_part}. "
        f"Routing category: {urgency.value}."
    )


def classify_triage(request: TriageRequest) -> TriageResponse:
    text = normalize_text(request.symptom_text)
    symptoms = extract_symptoms(text)

    emergency = find_emergency_matches(text)

    emergency_follow_up = has_positive_answer(
        request,
        {
            "trouble breathing",
            "difficulty breathing",
            "chest pain",
            "passed out",
            "unconscious",
            "severe bleeding",
        },
    )

    # Safety override: emergency rules always run first.
    if emergency.phrases or emergency_follow_up:
        matched = emergency.phrases.copy()

        if emergency_follow_up:
            matched.append("positive emergency follow-up answer")

        explanation = (
            "; ".join(emergency.explanations)
            if emergency.explanations
            else "A follow-up answer matched an emergency safety rule."
        )

        return TriageResponse(
            urgency_level=UrgencyLevel.EMERGENCY_WARNING,
            recommendation=(
                "Emergency warning: contact local emergency services "
                "or seek immediate emergency assistance."
            ),
            explanation=explanation,
            summary=create_summary(
                request,
                symptoms,
                UrgencyLevel.EMERGENCY_WARNING,
            ),
            red_flag_found=True,
            matched_red_flags=matched,
            extracted_symptoms=symptoms,
            confidence=1.0,
            classifier_source="RULE_BASED_SAFETY_OVERRIDE",
            requires_staff_review=True,
            disclaimer=DISCLAIMER,
        )

    urgent_matches = find_phrase_matches(text, URGENT_PHRASES)
    walk_in_matches = find_phrase_matches(text, WALK_IN_PHRASES)
    family_matches = find_phrase_matches(text, FAMILY_DOCTOR_PHRASES)
    self_care_matches = find_phrase_matches(text, SELF_CARE_PHRASES)

    if request.severity >= 5 or urgent_matches:
        urgency = UrgencyLevel.URGENT_CARE
        recommendation = (
            "Prompt assessment at an urgent-care service is recommended."
        )
        explanation = (
            "High reported severity or an urgent routing phrase was detected."
        )
        confidence = 0.90

    elif request.severity == 4:
        urgency = UrgencyLevel.URGENT_CARE
        recommendation = (
            "A prompt assessment is recommended because the reported "
            "severity is high."
        )
        explanation = "The patient selected severity 4 out of 5."
        confidence = 0.82

    elif walk_in_matches:
        urgency = UrgencyLevel.WALK_IN_CLINIC
        recommendation = (
            "A walk-in clinic or similar same-day clinic assessment "
            "may be appropriate."
        )
        explanation = (
            "Matched walk-in routing phrases: "
            + ", ".join(walk_in_matches)
        )
        confidence = 0.80

    elif family_matches:
        urgency = UrgencyLevel.FAMILY_DOCTOR
        recommendation = (
            "Arrange a non-emergency appointment with a family doctor "
            "or regular healthcare provider."
        )
        explanation = (
            "Matched family-doctor routing phrases: "
            + ", ".join(family_matches)
        )
        confidence = 0.78

    elif self_care_matches and request.severity <= 2:
        urgency = UrgencyLevel.SELF_CARE
        recommendation = (
            "The intake may be appropriate for self-care monitoring. "
            "Seek professional advice if symptoms worsen or continue."
        )
        explanation = (
            "Only mild routing phrases and low severity were reported."
        )
        confidence = 0.75

    elif symptoms:
        urgency = UrgencyLevel.FAMILY_DOCTOR
        recommendation = (
            "The information should be reviewed by a regular healthcare "
            "provider."
        )
        explanation = (
            "Symptoms were identified, but no emergency or urgent "
            "routing rule matched."
        )
        confidence = 0.60

    else:
        urgency = UrgencyLevel.NEEDS_REVIEW
        recommendation = (
            "The information is too general for automatic routing. "
            "A clinic staff member should review the case."
        )
        explanation = (
            "No reliable symptom or routing phrase was extracted "
            "from the submitted text."
        )
        confidence = 0.35

    return TriageResponse(
        urgency_level=urgency,
        recommendation=recommendation,
        explanation=explanation,
        summary=create_summary(request, symptoms, urgency),
        red_flag_found=False,
        matched_red_flags=[],
        extracted_symptoms=symptoms,
        confidence=confidence,
        classifier_source="RULE_BASED_NLP",
        requires_staff_review=(
            urgency == UrgencyLevel.NEEDS_REVIEW
            or confidence < 0.65
        ),
        disclaimer=DISCLAIMER,
    )