EMERGENCY_PHRASES = {
    "difficulty breathing": "Difficulty breathing was reported",
    "shortness of breath": "Shortness of breath was reported",
    "cannot breathe": "Unable to breathe was reported",
    "can't breathe": "Unable to breathe was reported",
    "chest pain": "Chest pain was reported",
    "pain in chest": "Chest pain was reported",
    "chest discomfort": "Chest discomfort was reported",
    "chest pressure": "Chest pressure was reported",
    "pressure in chest": "Chest pressure was reported",
    "chest tightness": "Chest tightness was reported",
    "tightness in chest": "Chest tightness was reported",
    "chest squeezing": "Chest squeezing was reported",
    "chest heaviness": "Chest heaviness was reported",
    "heart pain": "Possible heart or chest pain was reported",
    "pain in heart": "Possible heart or chest pain was reported",
    "pain in my heart": "Possible heart or chest pain was reported",
    "pain in the heart": "Possible heart or chest pain was reported",
    "pain around heart": "Possible heart or chest pain was reported",
    "pain around my heart": "Possible heart or chest pain was reported",
    "severe chest pain": "Severe chest pain was reported",
    "crushing chest pain": "Crushing chest pain was reported",
    "unconscious": "Loss of consciousness was reported",
    "not responding": "Altered consciousness was reported",
    "face drooping": "Possible stroke-like symptom was reported",
    "slurred speech": "Possible stroke-like symptom was reported",
    "sudden weakness": "Possible stroke-like symptom was reported",
    "severe bleeding": "Severe bleeding was reported",
    "bleeding won't stop": "Uncontrolled bleeding was reported",
    "throat swelling": "Possible serious allergic reaction was reported",
    "severe allergic reaction": "Possible serious allergic reaction was reported",
}

URGENT_PHRASES = {
    "high fever",
    "persistent vomiting",
    "severe pain",
    "worsening quickly",
    "unable to keep fluids down",
    "deep cut",
    "possible fracture",
    "head injury",
    "severe dehydration",
}

WALK_IN_PHRASES = {
    "ear infection",
    "sore throat",
    "skin rash",
    "painful urination",
    "minor burn",
    "moderate fever",
    "persistent cough",
    "sinus pain",
}

FAMILY_DOCTOR_PHRASES = {
    "recurring headache",
    "ongoing fatigue",
    "mild back pain",
    "medication review",
    "ongoing joint pain",
    "sleep problem",
    "symptoms for several weeks",
}

SELF_CARE_PHRASES = {
    "mild cold",
    "runny nose",
    "mild cough",
    "minor headache",
    "small cut",
    "mild muscle pain",
    "mild sore throat",
}

KNOWN_SYMPTOMS = {
    "chest pain",
    "pain in chest",
    "chest discomfort",
    "chest pressure",
    "chest tightness",
    "heart pain",
    "pain in heart",
    "pain in my heart",
    "pain in the heart",
    "pain around heart",
    "pain around my heart",
    "shortness of breath",
    "headache",
    "fever",
    "cough",
    "sore throat",
    "vomiting",
    "nausea",
    "dizziness",
    "rash",
    "back pain",
    "abdominal pain",
    "fatigue",
    "bleeding",
    "swelling",
    "weakness",
    "difficulty breathing",
}